require "json"
require "yaml"
require "net/http"
require "nokogiri"
require "time"
require "rsolr"
require "faraday"
require "htmlentities"
require "delegate"
require "erb"

require_relative "solr_indexer/term"
require_relative "solr_indexer/nodes"
require_relative "solr_indexer/literal_field"
require_relative "solr_indexer/simple_field"
require_relative "solr_indexer/bundle_field"
require_relative "solr_indexer/prefixed_field"
require_relative "solr_indexer/multi_source_field"

require_relative "solr_indexer/blogs"
require_relative "solr_indexer/staff"
require_relative "solr_indexer/submitter"

require_relative "solr_indexer/tag_array"
require_relative "solr_indexer/metadata"
require_relative "solr_indexer/lib_guides"
